package az.edu.turing.dao.entity;

import java.io.InvalidClassException;

public enum Cities {
    LONDON, PARIS, NEW_YORK, TOKYO, DUBAI, ISTANBUL, SINGAPORE, KUALA_LUMPUR, SEOUL, HONG_KONG, BAKU, BANGKOK,
    LOS_ANGELES, BARCELONA, ROME, MILAN, MADRID, BERLIN, MUNICH, FRANKFURT, AMSTERDAM, VIENNA, ZURICH, GENEVA,
    BRUSSELS, COPENHAGEN, STOCKHOLM, OSLO, HELSINKI, WARSAW, PRAGUE, BUDAPEST, ATHENS, LISBON, MOSCOW, SAINT_PETERSBURG,
    KIEV, MINSK, RIGA, TALLINN, VILNIUS, SOFIA, BUCHAREST, BELGRADE, ZAGREB, SARAJEVO, SKOPJE, TIRANA, PRISTINA, PODGORICA,
    CHISINAU, TBILISI, ASTANA, ALMATY, TASHKENT, ASHGABAT, BISHKEK, DUSHANBE, KHUJAND, ANKARA, TEHRAN, BAGHDAD,
    BEIRUT, JERUSALEM, AMMAN, CAIRO, TRIPOLI, TUNIS, ALGIERS, RABAT, CASABLANCA, DAKAR, BAMAKO, OUAGADOUGOU,
    NIAMEY, KHARTOUM, ADDIS_ABABA, NAIROBI, DAR_ES_SALAAM, KAMPALA, KIGALI, BUJUMBURA, DODOMA, LUSAKA, HARARE, GABORONE,
    MAPUTO, WINDHOEK, CAPE_TOWN, BLOEMFONTEIN, JOHANNESBURG, PORT_ELIZABETH, EAST_LONDON, MBABANE, MASERU,
    VICTORIA, PORT_LOUIS;


    public static Cities fromString(String name) {
        try {

            return Cities.fromString(name.trim().replace(" ", "_").toUpperCase());
        } catch (IllegalArgumentException e) {
            System.out.println("invalid city name: " + name);

            return null;
        }
    }
}